sudo: required

services:
 - docker

before_install:
 - docker build -t pozzallo/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true pozzallo/docker-react-app npm run test