sudo: required

services:
 - docker

before_install:
 - docker build -t pozzallo/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true pozzallo/docker-react-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-415501347369"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: $AWS_SECRET_KEY
